export const GETPRODUCTS_INITIATE = 'GETPRODUCTS_INITIATE'
export const GETPRODUCTS_SUCCESS = 'GETPRODUCTS_SUCCESS'
export const GETPRODUCTS_FAILURE = 'GETPRODUCTS_FAILURE'

export const GETPRODUCTBYID_INITIATE = 'GETPRODUCTBYID_INITIATE'
export const GETPRODUCTBYID_SUCCESS = 'GETPRODUCTBYID_SUCCESS'
export const GETPRODUCTBYID_FAILURE = 'GETPRODUCTBYID_FAILURE'